version: '3'

services:
  api-yexley-net-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'

  # this doesn't work for some reason, would be nice to figure out why
  api-yexley-net:
    build: .
    command: yarn run start:dev
    ports:
      - "7100:7100"
    depends_on:
      - api-yexley-net-db
    volumes:
      - ./src:/app/src
    env_file:
      - .env
